version: '3.9'

services:
  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
    - pg-go-web:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pw

volumes:
  pg-go-web:
